### ISSUE TITLE
Error when deleting projects

### ISSUE THREAD

**Issue by fallenbeck** [fallenbeck/tt#2]
When I try to delete a project a TypeError exception is thrown:

```sh
Traceback (most recent call last):
  File "/Users/fallenbeck/bin/tt", line 708, in <module>
    del_project()
  File "/Users/fallenbeck/bin/tt", line 441, in del_project
    project_id = _get_project_id(data, sys.argv[2:])
  File "/Users/fallenbeck/bin/tt", line 93, in _get_project_id
    if project_id_or_name in data["projects"].keys():
TypeError: unhashable type: 'list'
```

**Comment by fallenbeck** [comment]
fixed in 6b5f46d931bdf230e85a4137b49600307468a899
